[fix] Make @types/node-fetch a production dep
Fixes the following build error that happens because this line: https://github.com/telegraf/telegraf/blob/57f16c70901e3c73b9ab67933a926fedf7a2b11d/src/core/network/client.ts#L28 re-exporting `RequestInit` from `@types/node-fetch`

```
packages/telegram build:w: node_modules/.pnpm/telegraf@4.0.0/node_modules/telegraf/typings/core/network/client.d.ts(3,29): error TS7016: Could not find a declaration file for module 'node-fetch'. '/media/Library/home/mkr/Code/telecraft/telecraft/packages/telegram/node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
```